// src/fortress/languages.ts

export type LanguageType = 'en' | 'vi';

export const FORTRESS_LANG = {
  en: {
    // Lobby & Room Setup
    lobbyTitle: "🏰 FORTRESS MULTIPLAYER LOBBY",
    enterName: "Enter player name...",
    enterCode: "Enter 4-letter Room Code...",
    chooseDifficulty: "Choose Starting Difficulty Class:",
    difficultyLvl: "Level",
    level1Desc: "Hero of Prophecy (Easy) - 50 Warriors, 3 Scouts, 2 Clerics, 500 GP, 30 Rations, Dragon Sword",
    level2Desc: "Seasoned Commander (Normal) - 30 Warriors, 2 Scouts, 1 Cleric, 300 GP, 20 Rations",
    level3Desc: "Daring Explorer (Hard) - 15 Warriors, 1 Scout, 1 Cleric, 150 GP, 10 Rations",
    level4Desc: "Solo Survivor (Legendary) - 5 Warriors, 1 Scout, 0 Cleric, 50 GP, 5 Rations",
    mapDifficulty: "Map Difficulty Scale (1-20):",
    createRoom: "👑 CREATE NEW ROOM",
    joinRoom: "⚔️ JOIN EXISTING ROOM",
    activePlayers: "Connected Players in Lobby:",
    backToLobby: "← Exit to Lobby",

    // Terrain Names & Tooltips
    terrainPlains: "Plains",
    terrainForest: "Forest",
    terrainMountain: "Mountain",
    terrainLake: "Lake",
    terrainTown: "Town",
    terrainSanctuary: "Sanctuary",
    terrainCitadel: "Citadel",
    costLabel: "Cost",
    unexploredLabel: "Unexplored (Fog of War)",

    // Header & Nav
    headerTitle: "🎮 WITCH KING OVERWORLD ENGINE DECK v0.0.3-ALPHA",
    headerSub: "Live Navigation & Town Marketplace Integration",
    seedLabel: "Seed Key:",
    diffLabel: "Difficulty (1-4):",
    posLabel: "📍 Pos:",
    mfLabel: "⚡ MF:",
    rationsLabel: "🌾 Rations:",
    goldLabel: "💰 Gold:",
    warriorsLabel: "⚔️ Warriors:",
    scoutsLabel: "🏹 Scouts:",
    mulesLabel: "🫏 Mules:",
    raftLabel: "🚣 Raft:",
    yes: "YES",
    no: "NO",
    sightLabel: "Sight:",
    navTip: "* Tap highlighted dashed tiles to navigate. Tap current tile to rest/re-enter town.",
    endTurnBtn: "🔒 LOCK & END TURN",
    logHeader: "Transaction Log Ticker:",
    
    // Marketplace & Haggling
    shopTitle: "🏰 TOWN MARKETPLACE",
    yourGold: "💰 Your Gold:",
    bargainFor: "Bargain for:",
    yourBid: "Your Bid:",
    quote: "Quote:",
    offerBtn: "🤝 OFFER BID",
    exitShopBtn: "Exit Shop (No Purchase)",
    shopWelcome: "Welcome to the Town Marketplace!",
    notEnoughGold: "⚠️ You do not have enough Gold for this bid!",
    
    // Shop Items
    itemRationsName: "Pack of Rations (10x)",
    itemRationsDesc: "10 food supplies for troop upkeep.",
    itemWarriorsName: "Warriors (5x)",
    itemWarriorsDesc: "Frontline melee combat troops.",
    itemScoutsName: "Scout Specialist",
    itemScoutsDesc: "Increases vision radius and camp evasion.",
    itemClericsName: "Cleric Healer",
    itemClericsDesc: "Provides post-combat passive healing.",
    itemRaidersName: "Raider Specialist",
    itemRaidersDesc: "Stealth unit used to raid opponent camps.",
    itemMulesName: "Pack Mule",
    itemMulesDesc: "Increases gold carrying capacity (+50 GP).",
    itemRaftName: "River Raft + 4 Mules",
    itemRaftDesc: "Allows sailing across Lake tiles.",
    itemWizardName: "Grand Wizard",
    itemWizardDesc: "Grants +20% party combat strength & spellfire.",
    itemTeleportName: "Teleport Scroll",
    itemTeleportDesc: "Instant transport to safe havens or pins.",
    itemSeeingName: "Spell of Seeing Scroll",
    itemSeeingDesc: "Temporarily reveals unexplored regions.",

    // Merchant Feedback
    merchantHappy: "😊 Merchant accepts your fair offer gladly!",
    merchantGroan: "🙂 Merchant groans slightly, but agrees to the deal.",
    merchantCounter: "🤨 Merchant rejects bid. Counter offer:",
    merchantAngry: "😡 'Get out of my shop, you cheap insult!' Merchant kicks you out!",
    merchantOffended: "😠 Merchant is offended by your lowball. Hard counter:",

    // Modals
    transSuccess: "🎉 TRANSACTION SUCCESSFUL",
    ejectedTitle: "🚨 EJECTED FROM MARKETPLACE",
    acquiredText: "Item acquired:",
    forText: "for",
    penaltyText: "Penalty:",
    penaltyDetail: "-1 Movement Factor (MF)",
    claimContinueBtn: "✅ OK, CLAIM ITEM & CONTINUE",
    leaveShopBtn: "🚪 OK, LEAVE MARKETPLACE",

    // PvE Combat & Harvesting
    combatTitle: "⚔️ WILD MONSTER ENCOUNTER",
    surpriseTitle: "🚨 AMBUSH SURPRISE DETECTED!",
    surpriseMsg: "Your scouts spotted monsters ahead! Would you like to retreat back?",
    retreatBtn: "🏃 RETREAT (SAFETY)",
    fightBtn: "⚔️ ENGAGE IN COMBAT",
    attackRoundBtn: "🎲 ATTACK ROUND",
    victoryTitle: "🎉 COMBAT VICTORY!",
    defeatTitle: "💀 FRONTLINE COLLAPSED!",
    harvestBtn: "🍖 HARVEST MEAT FOR RATIONS",
    skipHarvestBtn: "⏭️ SKIP HARVEST & LEAVE",
    safeMeatYield: "Safe Meat Harvested:",
    toxicMeatWarning: "⚠️ TOXIC MEAT WARNING: Harvesting yields 2x Rations, but carries a poisoning risk!",
    poisonedMsg: "🤢 POISONED! Uncooked toxic meat weakened your party (-1 MF next turn)!",
    cleanEatMsg: "😋 Scouts prepared the meat safely! Gained rations with 0 poison!",
    inedibleMsg: "🦴 Inedible carcass. No meat can be harvested.",
    goldLootGained: "Gold looted from monsters:",

    // Monster Names
    monsterKobold: "Kobold Scout",
    monsterGoblin: "Goblin Frontliner",
    monsterBugbear: "Bugbear Marauder",
    monsterOrc: "Orc Berserker",
    monsterOwlbear: "Owlbear Beast",
    monsterTroll: "Cave Troll",
    monsterGargoyle: "Stone Gargoyle",
    monsterGiant: "Frost Giant Colossus",
    monsterChimera: "Mountain Chimera",
    monsterMindFlayer: "Mind Flayer",
    monsterDisplacer: "Displacer Beast",
    monsterCube: "Gelatinous Cube",
    monsterDragon: "Ancient Red Dragon",
    monsterBeholder: "Beholder",
    monsterTarrasque: "The Tarrasque",
    monsterZombie: "Zombie",
    monsterSkeleton: "Skeleton Warrior",
    monsterMimic: "Mimic Chest",
    monsterIronGolem: "Iron Golem",
    monsterLich: "Shadow Lich",

    // Action Logs
    logSpawn: "🏁 Map Generated. Spawned at Hub",
    logMoved: "👟 Moved to",
    logReentered: "🏰 Re-entered Town Marketplace (-1 MF)! Opening shop...",
    logRested: "⛺ Rested at current tile",
    logEnteredTown: "🏰 Entered Town Marketplace! Opening Merchant Shop...",
    logPurchased: "🛒 Purchased",
    logEjected: "😡 Merchant ejected you for lowballing! Lost 1 MF!",
    logTurnEnded: "🌙 Turn Ended. Consumed",
    logRations: "Rations.",
    logStarvation: "⚠️ STARVATION! Lost",
    logWarriorsLost: "Warriors due to lack of food!",
    logNewTurn: "☀️ New Turn Started! Movement refreshed to 10 MF.",
    logRelicFound: "✨ ANCIENT RELIC FOUND:",
    logEncounterTrigger: "⚔️ Wild Encounter Triggered! Battle initiated!",
    logCombatWon: "🏆 Defeated monster group! Victory secured.",
    logRetreated: "🏃 Safely retreated from wild encounter."
  },
  vi: {
    // Lobby & Room Setup
    lobbyTitle: "🏰 PHÒNG CHỜ ĐẤU TRƯỜNG PHÁO ĐÀI",
    enterName: "Nhập tên người chơi...",
    enterCode: "Nhập mã phòng 4 chữ cái...",
    chooseDifficulty: "Chọn Cấp Độ Khởi Đầu:",
    difficultyLvl: "Cấp",
    level1Desc: "Anh Hùng Tiên Tri (Dễ) - 50 Lính, 3 Trinh sát, 2 Mục sư, 500 Vàng, 30 Lương, Kiếm Diệt Rồng",
    level2Desc: "Tướng Lĩnh Dày Dạn (Thường) - 30 Lính, 2 Trinh sát, 1 Mục sư, 300 Vàng, 20 Lương",
    level3Desc: "Thám Hiểm Liều Lĩnh (Khó) - 15 Lính, 1 Trinh sát, 1 Mục sư, 150 Vàng, 10 Lương",
    level4Desc: "Sinh Tồn Đơn Lộc (Huyền Thoại) - 5 Lính, 1 Trinh sát, 0 Mục sư, 50 Vàng, 5 Lương",
    mapDifficulty: "Mức Khó Bản Đồ (1-20):",
    createRoom: "👑 TẠO PHÒNG MỚI",
    joinRoom: "⚔️ VÀO PHÒNG CÓ SẴN",
    activePlayers: "Người Chơi Đang Trong Phòng:",
    backToLobby: "← Trở Về Phòng Chờ",

    // Terrain Names & Tooltips
    terrainPlains: "Đồng Bằng",
    terrainForest: "Rừng Rậm",
    terrainMountain: "Núi Cao",
    terrainLake: "Hồ Nước",
    terrainTown: "Thành Trị",
    terrainSanctuary: "Thánh Địa",
    terrainCitadel: "Pháo Đài",
    costLabel: "Chi Phí",
    unexploredLabel: "Chưa Thám Hiểm (Sương Mù)",

    // Header & Nav
    headerTitle: "🎮 ĐẤU TRƯỜNG PHÁO ĐÀI VƯƠNG GIẢ v0.0.3-ALPHA",
    headerSub: "Mô Phỏng Di Chuyển & Chợ Thương Nhân Trực Tiếp",
    seedLabel: "Mã Map Seed:",
    diffLabel: "Độ Khó (1-4):",
    posLabel: "📍 Vị Trí:",
    mfLabel: "⚡ Thể Lực (MF):",
    rationsLabel: "🌾 Lương Thực:",
    goldLabel: "💰 Vàng:",
    warriorsLabel: "⚔️ Binh Lính:",
    scoutsLabel: "🏹 Trinh Sát:",
    mulesLabel: "🫏 Lừa Thồ:",
    raftLabel: "🚣 Bè Gỗ:",
    yes: "CÓ",
    no: "KHÔNG",
    sightLabel: "Tầm Nhìn:",
    navTip: "* Nhấp vào ô viền xanh để di chuyển. Nhấp ô hiện tại để nghỉ/vào lại chợ.",
    endTurnBtn: "🔒 KHÓA & KẾT THÚC LƯỢT",
    logHeader: "Nhật Ký Hành Động:",
    
    // Marketplace & Haggling
    shopTitle: "🏰 CHỢ THƯƠNG NHÂN THÀNH TRỊ",
    yourGold: "💰 Vàng Hiện Có:",
    bargainFor: "Trả giá cho:",
    yourBid: "Giá Bạn Trả:",
    quote: "Giá Thách:",
    offerBtn: "🤝 ĐẶT GIÁ NÀY",
    exitShopBtn: "Rời Chợ (Không Mua)",
    shopWelcome: "Chào mừng đến với Chợ Thành Trị!",
    notEnoughGold: "⚠️ Bạn không đủ Vàng để trả mức giá này!",

    // Shop Items
    itemRationsName: "Túi Lương Thực (10x)",
    itemRationsDesc: "10 phần ăn duy trì quân đội mỗi lượt.",
    itemWarriorsName: "Chiến Binh (5x)",
    itemWarriorsDesc: "Lực lượng chiến đấu giáp lá lá cận chiến.",
    itemScoutsName: "Trinh Sát Tinh Anh",
    itemScoutsDesc: "Tăng tầm nhìn bản đồ và né tránh đột kích.",
    itemClericsName: "Mục Sư Hồi Máu",
    itemClericsDesc: "Hồi phục vết thương quân sĩ sau trận đánh.",
    itemRaidersName: "Đạo Tặc Tập Kích",
    itemRaidersDesc: "Đơn vị lén lút cướp phá doanh trại đối thủ.",
    itemMulesName: "Lừa Thồ Hàng",
    itemMulesDesc: "Tăng sức chứa vàng túi đồ (+50 Vàng).",
    itemRaftName: "Bè Gỗ Vượt Sông + 4 Lừa",
    itemRaftDesc: "Cho phép di chuyển băng qua các ô Hồ Nước.",
    itemWizardName: "Đại Pháp Sư",
    itemWizardDesc: "Tăng +20% sức mạnh chiến đấu & chưởng lửa.",
    itemTeleportName: "Cuộn Bí Kíp Dịch Chuyển",
    itemTeleportDesc: "Dịch chuyển tức thời tới nơi an toàn.",
    itemSeeingName: "Phép Thuật Mở Tầm Nhìn",
    itemSeeingDesc: "Tạm thời soi sáng vùng đất bị mây mù che phủ.",

    // Merchant Feedback
    merchantHappy: "😊 Thương nhân vui vẻ đồng ý bán ngay lập tức!",
    merchantGroan: "🙂 Thương nhân cằn nhằn một chút nhưng chấp nhận bán.",
    merchantCounter: "🤨 Thương nhân chê rẻ. Giá mặc cả lại:",
    merchantAngry: "😡 'Cút khỏi tiệm tao ngay, đồ keo kiệt!' Thương nhân đuổi bạn ra ngoài!",
    merchantOffended: "😠 Thương nhân tự ái vì bị ép giá quá đáng. Đưa ra giá cứng:",

    // Modals
    transSuccess: "🎉 GIAO DỊCH THÀNH CÔNG",
    ejectedTitle: "🚨 BỊ BỊT MIỆNG ĐUỔI KHỎI CHỢ",
    acquiredText: "Đã sở hữu:",
    forText: "với giá",
    penaltyText: "Hình phạt:",
    penaltyDetail: "-1 Điểm Thể Lực (MF)",
    claimContinueBtn: "✅ OK, NHẬN MÓN HÀNG & TIẾP TỤC",
    leaveShopBtn: "🚪 OK, RỜI KHỎI CHỢ",

    // PvE Combat & Harvesting
    combatTitle: "⚔️ ĐỤNG ĐỘ QUÁI VẬT HOANG DÃ",
    surpriseTitle: "🚨 PHÁT HIỆN ĐỘT KÍCH BẤT NGỜ!",
    surpriseMsg: "Trinh sát phát hiện quái vật phía trước! Bạn có muốn rút lui an toàn?",
    retreatBtn: "🏃 RÚT LUI AN TOÀN",
    fightBtn: "⚔️ LAO VÀO NGHÊNH CHIẾN",
    attackRoundBtn: "🎲 ĐỔ XÚC XẮC TẤN CÔNG",
    victoryTitle: "🎉 CHIẾN THẮNG RỰC RỠ!",
    defeatTitle: "💀 QUÂN TIỀN TUYẾN THẤT THỦ!",
    harvestBtn: "🍖 THU HOẠCH THỊT QUÁI LÀM LƯƠNG THỰC",
    skipHarvestBtn: "⏭️ BỎ QUA & RỜI ĐI",
    safeMeatYield: "Lương thực sạch thu hoạch được:",
    toxicMeatWarning: "⚠️ CẢNH BÁO THỊT ĐỘC: Thu hoạch gấp đôi lương thực nhưng có nguy cơ trúng độc!",
    poisonedMsg: "🤢 TRÚNG ĐỘC! ĂN THỊT ĐỘC CHƯA CHẾ BIẾN LÀM SUY YẾU CƠ THỂ (-1 MF lượt sau)!",
    cleanEatMsg: "😋 Trinh sát đã chế biến sạch sẽ! Thu hoạch lương thực an toàn!",
    inedibleMsg: "🦴 Xác quái vật rỗng/không thể ăn được.",
    goldLootGained: "Vàng cướp được từ quái vật:",

    // Monster Names
    monsterKobold: "Trinh Sát Kobold",
    monsterGoblin: "Lính Tiên Phong Goblin",
    monsterBugbear: "Kẻ Cướp Bugbear",
    monsterOrc: "Cuồng Chiến Binh Orc",
    monsterOwlbear: "Quái Bố Owlbear",
    monsterTroll: "Troll Hang Động",
    monsterGargoyle: "Quỷ Đá Gargoyle",
    monsterGiant: "Khổng Lồ Băng Băng",
    monsterChimera: "Quái Thú Chimera",
    monsterMindFlayer: "Quỷ Hút Não Mind Flayer",
    monsterDisplacer: "Báo Biến Hình Displacer",
    monsterCube: "Khối Nhầy Gelatinous",
    monsterDragon: "Rồng Đỏ Cổ Đại",
    monsterBeholder: "Quái Nhãn Beholder",
    monsterTarrasque: "Thảm Họa Tarrasque",
    monsterZombie: "Thây Ma Zombie",
    monsterSkeleton: "Chiến Binh Xương Khô",
    monsterMimic: "Rương Ma Mimic",
    monsterIronGolem: "Người Sắt Iron Golem",
    monsterLich: "Chúa Tể Bóng Tối Lich",

    // Action Logs
    logSpawn: "🏁 Khởi tạo bản đồ. Xuất phát tại Thành Trị",
    logMoved: "👟 Đã bước tới",
    logReentered: "🏰 Vào lại Chợ Thành Trị (-1 MF)! Mở cửa tiệm...",
    logRested: "⛺ Tạm nghỉ tại ô hiện tại",
    logEnteredTown: "🏰 Đặt chân vào Thành Trị! Mở Chợ Thương Nhân...",
    logPurchased: "🛒 Đã mua",
    logEjected: "😡 Bị thương nhân đuổi vì trả giá quá bèo! Trừ 1 MF!",
    logTurnEnded: "🌙 Kết thúc lượt. Tiêu thụ",
    logRations: "phần lương thực.",
    logStarvation: "⚠️ CHẠY ĂN TỪNG BỮA! Mất",
    logWarriorsLost: "Chiến Binh do chết đói!",
    logNewTurn: "☀️ Bắt đầu lượt mới! Thể lực hồi phục 10 MF.",
    logRelicFound: "✨ BẢO VẬT CỔ ĐẠI:",
    logEncounterTrigger: "⚔️ Đụng độ quái vật hoang dã! Bắt đầu giao tranh!",
    logCombatWon: "🏆 Tiêu diệt sạch quái vật! Giành chiến thắng.",
    logRetreated: "🏃 Rút lui an toàn khỏi quái vật hoang dã."
  }
};