// src/fortress/languages.ts
export type LanguageType = 'en' | 'vi';

export const FORTRESS_LANG = {
  en: {
    lobbyTitle: "Fortress of the Witch King 🏰",
    enterName: "What is your Hero's name?",
    chooseDifficulty: "Pick your starting supplies:",
    difficultyLvl: "Supply Package Level",
    mapDifficulty: "Map Hardness Level (1-20)",
    createRoom: "Create Secret Room 🔑",
    joinRoom: "Join Friends' Room 🤝",
    enterCode: "Enter 4-Digit Room Code",
    gameStart: "Let's Go! 🚀",
    waitingPlayers: "Waiting for other players to lock their turns...",
    goldLabel: "Gold Pieces 💰",
    rationsLabel: "Rations 🍖",
    warriors: "Warriors ⚔️",
    scouts: "Scouts 🏹",
    clerics: "Clerics 🩹",
    raiders: "Raiders 👥",
    wizards: "Wizards 🧙‍♂️",
    elves: "Elves 🧝‍♂️",
    dwarves: "Dwarves 🧔",
    mules: "Mules 🫏",
    raft: "Raft ⛵",
    backToLobby: "Back to Lobby",
    activePlayers: "Active Heroes in Room",
    readyToBegin: "Everyone is ready! Start the adventure!",
    level1Desc: "Hero of Prophecy (Easy) - Rich starting resources & Dragon Slayer Sword 🗡️",
    level2Desc: "Seasoned Commander (Normal) - Balanced starting resources 🛡️",
    level3Desc: "Daring Explorer (Hard) - Low resources, but earns higher final scores 🧭",
    level4Desc: "Solo Survivor (Legendary) - Extremely hard, starts with almost nothing 💀",
  },
  vi: {
    lobbyTitle: "Pháo Đài của Vua Phù Thủy 🏰",
    enterName: "Tên Anh Hùng của con là gì nào?",
    chooseDifficulty: "Chọn túi tiếp tế ban đầu nhé:",
    difficultyLvl: "Túi Tiếp Tế Cấp",
    mapDifficulty: "Mức mấp mô của bản đồ (1-20)",
    createRoom: "Tạo Phòng Bí Mật 🔑",
    joinRoom: "Vào Chơi Cùng Bạn 🤝",
    enterCode: "Nhập Mã Phòng 4 Chữ Cái",
    gameStart: "Xuất Phát Thôi! 🚀",
    waitingPlayers: "Đang chờ các bạn khác khóa lượt đi...",
    goldLabel: "Đồng Vàng 💰",
    rationsLabel: "Đồ Ăn 🍖",
    warriors: "Chiến Binh ⚔️",
    scouts: "Thám Thính 🏹",
    clerics: "Tu Sĩ Cứu Thương 🩹",
    raiders: "Đột Kích Sĩ 👥",
    wizards: "Pháp Sư 🧙‍♂️",
    elves: "Yêu Tinh Rừng 🧝‍♂️",
    dwarves: "Người Lùn Mỏ 🧔",
    mules: "Lừa Chở Đồ 🫏",
    raft: "Bè Gỗ ⛵",
    backToLobby: "Quay lại Sảnh",
    activePlayers: "Các Bạn Đang Chờ Trong Phòng",
    readyToBegin: "Tất cả đã sẵn sàng! Bắt đầu cuộc phiêu lưu thôi!",
    level1Desc: "Người Được Chọn (Dễ) - Nhiều lính nhất và có sẵn Kiếm Diệt Rồng quý hiếm 🗡️",
    level2Desc: "Đại Tướng Bản Lĩnh (Vừa) - Có quân lính vừa đủ để bắt đầu thám hiểm 🛡️",
    level3Desc: "Nhà Thám Hiểm Dũng Cảm (Khó) - Lính ít hơn nhưng điểm thưởng cuối game cực cao 🧭",
    level4Desc: "Chiến Binh Độc Hành (Siêu Khó) - Chỉ có 5 chiến binh hành trang siêu nghèo nàn 💀",
  }
};