// src/fortress/languages.ts

export type LanguageType = 'en' | 'vi';

export const FORTRESS_LANG = {
  en: {
    // Sandbox Tweaker
    sandboxTitle: "🧪 DEV SANDBOX ARMY TWEAKER",
    addWarriors: "+10 Warriors",
    addGold: "+500 Gold",
    addRations: "+20 Rations",
    addWizard: "+1 Wizard",

    // Lobby & Setup
    lobbyTitle: "🏰 FORTRESS OF THE WITCH KING",
    lobbySubtitle: "Create a private game room or enter a Room Code to join!",
    createRoom: "👑 CREATE NEW ROOM",
    createRoomBtn: "🏰 CREATE NEW ROOM",
    joinRoom: "⚔️ JOIN EXISTING ROOM",
    joinRoomBtn: "⚔️ JOIN EXISTING ROOM",
    roomCodeLabel: "Room Code:",
    enterRoomCodePrompt: "Enter 4-Letter Room Code (e.g. WKYG):",
    joinBtnText: "ENTER ROOM",
    backToMenuBtn: "⬅️ Back",
    hostBadge: "ROOM HOST 👑",
    guestBadge: "GUEST COMMANDER ⚔️",
    enterNamePrompt: "Commander Name:",
    chooseIconLabel: "Choose Hero Icon:",
    readyBtnText: "🟢 MARK AS READY",
    unreadyBtnText: "🔴 CANCEL READY",
    startGameBtnText: "⚔️ LAUNCH GAME DEMO",
    waitingForHost: "Waiting for Host to start the game...",
    waitingForPlayers: "Waiting for all players to click READY...",
    gameStartingNotice: "🚀 ALL PLAYERS READY! Initializing Map & Distributing Spawns...",
    mapSizeNotice: "Dynamic Map Grid Size:",
    playerCountLabel: "Room Roster:",
    enterName: "Enter player name...",
    enterCode: "Enter 4-letter Room Code...",
    chooseDifficulty: "Choose Starting Difficulty Class:",
    difficultyLvl: "Level",
    level1Desc: "Hero of Prophecy (Easy) - 50 Warriors, 3 Scouts, 2 Clerics, 500 GP, 30 Rations, Dragon Sword",
    level2Desc: "Seasoned Commander (Normal) - 30 Warriors, 2 Scouts, 1 Cleric, 300 GP, 20 Rations",
    level3Desc: "Daring Explorer (Hard) - 15 Warriors, 1 Scout, 1 Cleric, 150 GP, 10 Rations",
    level4Desc: "Solo Survivor (Legendary) - 5 Warriors, 1 Scout, 0 Cleric, 50 GP, 5 Rations",
    mapDifficulty: "Map Difficulty Scale (1-20):",
    activePlayers: "Connected Players in Lobby:",
    backToLobby: "← Exit to Lobby",

    // Terrain Names & Tooltips
    terrainPlains: "Plains",
    terrainForest: "Forest",
    terrainMountain: "Mountain",
    terrainLake: "Lake",
    terrainTown: "Town",
    terrainSanctuary: "Sanctuary",
    terrainCitadel: "Citadel",
    costLabel: "Cost",
    unexploredLabel: "Unexplored (Fog of War)",

    // Viewport Controls
    zoomIn: "🔍 Zoom In",
    zoomOut: "🔍 Zoom Out",
    centerCam: "🎯 Center Player",

    // Header & Nav
    headerTitle: "🎮 WITCH KING OVERWORLD ENGINE DECK v0.0.3-ALPHA",
    headerSub: "Live Navigation & Town Marketplace Integration",
    seedLabel: "Seed Key:",
    diffLabel: "Difficulty (1-4):",
    posLabel: "📍 Pos:",
    mfLabel: "⚡ MF:",
    rationsLabel: "🌾 Rations:",
    goldLabel: "💰 Gold:",
    warriorsLabel: "⚔️ Warriors:",
    scoutsLabel: "🏹 Scouts:",
    mulesLabel: "🫏 Mules:",
    wizardsLabel: "🧙‍♂️ Wizard:",
    clericsLabel: "📿 Clerics:",
    raidersLabel: "🗡️ Raiders:",
    raftLabel: "🚣 Raft:",
    yes: "YES",
    no: "NO",
    sightLabel: "Sight:",
    navTip: "* Tap highlighted dashed tiles to navigate. Tap current tile to rest/re-enter town.",
    endTurnBtn: "🔒 LOCK & END TURN",
    logHeader: "Transaction Log Ticker:",
    
    // Marketplace & Haggling
    shopTitle: "🏰 TOWN MARKETPLACE",
    yourGold: "💰 Your Gold:",
    bargainFor: "Bargain for:",
    yourBid: "Your Bid:",
    quote: "Quote:",
    offerBtn: "🤝 OFFER BID",
    exitShopBtn: "Exit Shop (No Purchase)",
    shopWelcome: "Welcome to the Town Marketplace!",
    notEnoughGold: "⚠️ You do not have enough Gold for this bid!",
    
    // Shop Items
    itemRationsName: "Pack of Rations (10x)",
    itemRationsDesc: "10 food supplies for troop upkeep.",
    itemWarriorsName: "Warriors (5x)",
    itemWarriorsDesc: "Frontline melee combat troops.",
    itemScoutsName: "Scout Specialist",
    itemScoutsDesc: "Increases vision radius and camp evasion.",
    itemClericsName: "Cleric Healer",
    itemClericsDesc: "Provides post-combat passive healing.",
    itemRaidersName: "Raider Specialist",
    itemRaidersDesc: "Stealth unit used to raid opponent camps.",
    itemMulesName: "Pack Mule",
    itemMulesDesc: "Increases gold carrying capacity (+50 GP).",
    itemRaftName: "River Raft + 4 Mules",
    itemRaftDesc: "Allows sailing across Lake tiles.",
    itemWizardName: "Grand Wizard",
    itemWizardDesc: "Grants +20% party combat strength & spellfire.",
    itemTeleportName: "Teleport Scroll",
    itemTeleportDesc: "Instant transport to anywhere.",
    itemSeeingName: "Spell of Seeing Scroll",
    itemSeeingDesc: "Temporarily reveals unexplored regions.",

    // Merchant Feedback
    merchantHappy: "😊 Merchant accepts your fair offer gladly!",
    merchantGroan: "🙂 Merchant groans slightly, but agrees to the deal.",
    merchantCounter: "🤨 Merchant rejects bid. Counter offer:",
    merchantAngry: "😡 'Get out of my shop, you cheap insult!' Merchant kicks you out!",
    merchantOffended: "😠 Merchant is offended by your lowball. Hard counter:",

    // Modals & Citadel / Endgame
    transSuccess: "🎉 TRANSACTION SUCCESSFUL",
    ejectedTitle: "🚨 EJECTED FROM MARKETPLACE",
    acquiredText: "Item acquired:",
    forText: "for",
    penaltyText: "Penalty:",
    penaltyDetail: "-1 Movement Factor (MF)",
    claimContinueBtn: "✅ OK, CLAIM ITEM & CONTINUE",
    leaveShopBtn: "🚪 OK, LEAVE MARKETPLACE",
    citadelGateTitle: "🏰 CITADEL GATE SIEGE",
    citadelGateMsg: "You have arrived at the Witch King's Dark Citadel!",
    citadelHornBonus: "🎺 Horn of Opening detected! Citadel Gate breach chance boosted to 75%!",
    citadelNoHornWarn: "⚠️ No Horn of Opening! Siege relies entirely on Scout infiltrators!",
    citadelBreachSuccess: "💥 GATES BREACHED! Your forces storm into the Citadel keep!",
    citadelBreachFailed: "🛡️ GATES HELD FIRM! Citadel defenses repelled your siege (-1 MF)!",
    citadelSealedTitle: "🏰 CITADEL GATES SEALED!",
    citadelSealedMsg: "The dark gates rejected your entry attempt! (Horn grants 75% breach chance; Scouts grant 5% per Scout). Try again!",
    citadelTitle: "🏰 WITCH KING'S DARK CITADEL",
    citadelSubtitle: "Explore the 16 hidden chambers. Find the Witch King without triggering Teleporter Traps!",
    roomCleared: "CLEAR",
    teleportTrapTitle: "🌀 TELEPORTER TRAP TRIGGERED!",
    teleportTrapMsg: "An ancient arcane glyph flashed beneath your feet, warping your entire army back outside to the overworld map!",
    duelDefeatTitle: "💀 DEFEATED BY THE WITCH KING!",
    duelDefeatMsg: "The Dark Lord's ancient magic overwhelmed your champion! Your routed army retreats to a sanctuary to recover.",
    logCitadelReentered: "🏰 Re-entering the Dark Citadel...",
    roomSlain: "SLAIN",
    roomTrap: "TRAP",
    duelTitle: "⚔️ 1v1 FINAL DUEL: WITCH KING SHOWDOWN",
    duelSubtitle: "Best of 3 Rounds! Choose your tactical stance against the Dark Lord:",
    stanceBlade: "⚔️ Blade Attack",
    stanceShield: "🛡️ Shield Parry",
    stanceSpell: "🔮 Arcane Spell",
    duelRound: "Round",
    duelYouChose: "You chose",
    duelBossChose: "Witch King chose",
    roundWin: "🎉 Round Won!",
    roundLoss: "💀 Round Lost!",
    roundDraw: "🤝 Stance Draw!",
    witchKingTitle: "👑 THE WITCH KING EMERGES!",
    witchKingVictoryTitle: "👑 VICTORY! THE WITCH KING HAS FALLEN!",
    witchKingVictoryMsg: "You defeated the Shadow Lich, conquered the Dark Citadel, and claimed the Crown & Orb of Power! The Realm is saved!",
    claimVictoryBtn: "🏆 CLAIM SUPREME VICTORY",
    gameVictoryTitle: "🏆 REALM CHAMPION VICTORY!",
    victoryMsg: "You defeated the Witch King and claimed the Fortress Realm! Peace and glory are restored to your name!",
    opponentWonTitle: "💀 GAME OVER - DEFEAT!",
    opponentWonMsg: "A rival commander has slain the Witch King and claimed ultimate victory over the realm!",
    logWitchKingDefeated: "👑 WITCH KING SLAIN! Realm Champion Victory Secured!",
    logCitadelSealed: "⚠️ Citadel Gates sealed! Requires 🎺 Horn of Opening.",
    relicTitle: "🏛️ ANCIENT RELIC CLAIMED!",
    relicAcquiredMsg: "You defeated the Guardian Boss and claimed an Ancient Artifact!",
    relicBootsName: "🥾 Boots of Stealth (Forest/Mountain movement = 1 MF)",
    relicHornName: "🎺 Horn of Opening (Citadel Gate Bypass Key)",
    relicSwordName: "🗡️ Sword of Strength (+50% Party Combat Power)",
    relicArmorName: "🛡️ Armor of Defense (50% Casualty Reduction)",

    // PvE Combat & Harvesting
    combatTitle: "⚔️ WILD MONSTER ENCOUNTER",
    surpriseTitle: "🚨 AMBUSH SURPRISE DETECTED!",
    surpriseMsg: "Your scouts spotted monsters ahead!",
    spottedMonster: "Monsters Detected:",
    winRateEstimate: "Estimated Win Rate:",
    retreatBtn: "🏃 RETREAT (SAFETY)",
    fleeMidCombatBtn: "🏃 FLEE COMBAT (-1 MF)",
    fightBtn: "⚔️ ENGAGE IN COMBAT",
    attackRoundBtn: "🎲 ATTACK ROUND",
    victoryTitle: "🎉 COMBAT VICTORY!",
    defeatTitle: "💀 FRONTLINE COLLAPSED!",
    harvestBtn: "🍖 HARVEST MEAT FOR RATIONS",
    skipHarvestBtn: "⏭️ SKIP HARVEST & LEAVE",
    safeMeatYield: "Safe Meat Harvested:",
    toxicMeatWarning: "⚠️ TOXIC MEAT WARNING: Harvesting yields 2x Rations, but carries a poisoning risk!",
    poisonedMsg: "🤢 POISONED! Uncooked toxic meat weakened your party (-1 MF next turn)!",
    cleanEatMsg: "😋 Scouts prepared the meat safely! Gained rations with 0 poison!",
    inedibleMsg: "🦴 Inedible carcass. No meat can be harvested.",
    goldLootGained: "Gold looted from monsters:",
    droppedGoldWarn: "⚠️ Excess Gold dropped due to carrying capacity limit! Dropped",
    droppedGoldModalTitle: "📦 EXCESS GOLD DROPPED ON GROUND!",
    droppedGoldModalMsg: "Your army reached maximum carrying capacity! Excess gold was placed on the ground tile. Return here with Mules or Warriors to reclaim it.",
    droppedAmountLabel: "Gold Dropped on Ground:",
    locationLabel: "Coordinates:",
    pickupGoldLog: "💰 Recovered ground loot! Picked up",
    goldCollectedModalTitle: "💰 GROUND LOOT COLLECTED!",
    goldCollectedModalMsg: "Your troops recovered lost gold resting on this tile!",
    goldCollectedAmountLabel: "Gold Recovered:",

    // Scrolls & Raiding
    castSeeingBtn: "📜 Cast Spell of Seeing",
    playerNameLabel: "Player Name:",
    opponentsOnline: "Players in Room:",
    raidedByLog: "🚨 WARNING! Your camp was raided by",
    raidedYouLog: "🗡️ Stealth Raid Successful! You raided",
    raidModalTitle: "🚨 CAMP RAIDED BY ENEMY RAIDERS!",
    raidModalMsg: "An enemy raiding party infiltrated your camp under cover of darkness!",
    raidOutOfRange: "⚠️ Target player is out of raid stealth range (Must be within 3 tiles)!",
    raidedByLabel: "Raided by:",
    goldStolenLabel: "Gold Stolen:",
    mulesLootedLabel: "Pack Mules Looted:",
    raidThwartedLog: "🛡️ SENTRY SCOUTS INTERCEPTED RAID! Enemy raiders were spotted and driven off!",
    raidThwartedAttackerLog: "🚨 Raid thwarted! Enemy Scout sentries spotted your Raiders!",
    relicStolenLabel: "Legendary Relic Stolen:",
    townRumorTitle: "📜 TOWN & SANCTUARY RUMOR NETWORK",
    townRumorMsg: "Tavern bards and merchants whisper news of great deeds and raids across the realm:",
    logRumorClaimed: "defeated a Mountain Boss and claimed the",
    logRumorStolen: "stole the artifact",
    logRumorFrom: "from",
    opponentSpottedTitle: "🚨 ENEMY SPOTTED BY SCOUTS!",
    opponentSpottedMsg: "Your scouts spotted an enemy army in range!",
    drownModalTitle: "🌊 DROWNED IN DEEP LAKE!",
    drownModalMsg: "Your army attempted to cross water without a Raft! Heavy armor dragged troops under, losing all carried Gold. Survivors washed ashore nearby.",
    drownLog: "🌊 Drowned in Lake! Lost carried gold and washed ashore on adjacent land",
    teleportTargetPrompt: "🌀 SELECT TELEPORT DESTINATION: Click ANY land tile on the map (even in Fog of War)!",
    teleportCancelBtn: "❌ Cancel Teleport",
    castTeleportBtn: "🌀 Teleport",
    raidCampBtn: "🗡️ Raid Bandit Camp",
    logSeeingCast: "✨ Spell of Seeing cast! Unveiled fog of war across 8-tile radius!",
    logTeleportCast: "🌀 Teleport Scroll activated! Warped army safely!",
    logRaidSuccess: "🗡️ Stealth Raid Successful! Raiders stole +150 GP and +1 Mule!",
    logNoScrolls: "⚠️ You do not own any scrolls of this type!",

    // Monster Names
    monsterKobold: "Kobold Scout",
    monsterGoblin: "Goblin Frontliner",
    monsterBugbear: "Bugbear Marauder",
    monsterOrc: "Orc Berserker",
    monsterOwlbear: "Owlbear Beast",
    monsterTroll: "Cave Troll",
    monsterGargoyle: "Stone Gargoyle",
    monsterGiant: "Frost Giant Colossus",
    monsterChimera: "Mountain Chimera",
    monsterMindFlayer: "Mind Flayer",
    monsterDisplacer: "Displacer Beast",
    monsterCube: "Gelatinous Cube",
    monsterDragon: "Ancient Red Dragon",
    monsterBeholder: "Beholder",
    monsterTarrasque: "The Tarrasque",
    monsterZombie: "Zombie",
    monsterSkeleton: "Skeleton Warrior",
    monsterMimic: "Mimic Chest",
    monsterIronGolem: "Iron Golem",
    monsterLich: "Shadow Lich",

    // Action Logs & Manual
    logSpawn: "🏁 Map Generated. Spawned at Hub",
    logMoved: "👟 Moved to",
    logReentered: "🏰 Re-entered Town Marketplace (-1 MF)! Opening shop...",
    logRested: "⛺ Rested at current tile",
    logEnteredTown: "🏰 Entered Town Marketplace! Opening Merchant Shop...",
    logPurchased: "🛒 Purchased",
    logEjected: "😡 Merchant ejected you for lowballing! Lost 1 MF!",
    logTurnEnded: "🌙 Turn Ended. Consumed",
    logRations: "Rations.",
    logStarvation: "⚠️ STARVATION! Lost",
    logWarriorsLost: "Warriors due to lack of food!",
    logNewTurn: "☀️ New Turn Started! Movement refreshed to 3 MF.",
    waitingTurnLockTitle: "⏳ TURN LOCKED - WAITING FOR OTHER COMMANDERS",
    waitingTurnLockMsg: "You have locked your turn. Waiting for all players in the room to click LOCK & END TURN...",
    openManualBtn: "📖 GAME MANUAL & RULES",
    manualTitle: "📜 FORTRESS COMMANDER MANUAL",
    manualSecObjectiveTitle: "🏆 1. Main Objective & Victory",
    manualSecObjectiveText: "Compete against rival commanders in real-time. Search the realm for 4 legendary Relics, breach the Dark Citadel, and defeat the Witch King in a tactical 1v1 duel to claim supreme victory for your room!",
    manualSecMovementTitle: "👟 2. Movement, Upkeep & Survival",
    manualSecMovementText: "Every round grants 3 Movement Factors (MF). Orthogonal moves cost 1 MF, Diagonal moves cost 2 MF, and entering Mountains costs +1 extra MF. At turn end, your army consumes Rations (1 + Warriors/10). Running out of food causes starvation losses! Clerics passively heal wounded troops. Carrying a Raft requires 4 Mules to cross Lake tiles.",
    manualSecShopTitle: "🏰 3. Town Marketplace & Haggling",
    manualSecShopText: "Enter Town tiles to recruit troops, buy food, or purchase spell scrolls. You can make 1 purchase per visit. Drag the price slider to bid against quoted prices. Bidding below 70% risks insulting the merchant, getting you ejected from town and losing 1 MF!",
    manualSecMonstersTitle: "⚔️ 4. Monsters & Meat Harvesting",
    manualSecMonstersText: "Forests (28%) and Mountains (80%) trigger wild monster encounters. After winning, harvest carcasses for Rations: EDIBLE monsters are 100% safe; TOXIC monsters give 2x Rations but carry a poisoning risk (-1 MF next turn); INEDIBLE beasts yield 0 food. Each Scout reduces toxic meat poison risk by 5%!",
    manualSecRelicsTitle: "🏛️ 5. Ancient Relics (Witch King's Bane)",
    manualSecRelicsText: "Defeat Mountain Guardian Bosses to claim 4 global artifacts:\n• 🥾 Boots of Stealth: Reduces Forest & Mountain movement to 1 MF.\n• 🗡️ Sword of Strength: Boosts party Combat Power by +50%.\n• 🛡️ Armor of Defense: Cuts army battle casualties by 50%.\n• 🎺 Horn of Opening: Increases Citadel Gate breach success to 75%.",
    manualSecRaidingTitle: "🗡️ 6. PvP Stealth Raids & Sentries",
    manualSecRaidingText: "When within 3 tiles of an opponent's camp, deploy Raiders to steal Gold, Mules, and active Relics! Defending commanders with Scouts have a 20% sentry chance per Scout to intercept and drive off incoming Raiders. Stolen relics trigger tavern rumors in Towns!",
    manualSecCitadelTitle: "🏰 7. Citadel Infiltration & Final Duel",
    manualSecCitadelText: "Reach the Citadel tile and breach its gates using the Horn (75% chance) or Scouts. Inside, navigate 16 hidden chambers while avoiding Teleporter Traps that warp you back out! Reveal the Witch King to trigger a Best-of-3 Tactical Stance Duel: Blade (⚔️) beats Spell (🔮), Spell beats Shield (🛡️), and Shield beats Blade!",
    logRelicFound: "✨ ANCIENT GUARDIAN SPOTTED! A powerful boss defends the legendary artifact!",
    logEncounterTrigger: "⚔️ Wild Encounter Triggered! Battle initiated!",
    logCombatWon: "🏆 Defeated monster group! Victory secured.",
    logRetreated: "🏃 Safely retreated from wild encounter.",

    // Diplomacy & Parley Strings
    parleyTitle: "🤝 NEUTRAL ENCOUNTER PARLEY",
    parleyElfMsg: "An ancient warband of Elven Rangers emerges from the forest canopy!",
    parleyDwarfMsg: "A clan of Dwarven Berserkers marches down from the mountain peaks!",
    recruitElvesBtn: "🧝‍♂️ Recruit Elves (+5 Troops)",
    recruitDwarvesBtn: "🪓 Recruit Dwarves (+5 Troops)",
    attackParleyBtn: "⚔️ Attack Warband",
    ignoreParleyBtn: "🚶 Walk Away Safely",
    sendPeaceBtn: "🕊️ Send Peace Messenger",
    peaceModalTitle: "🕊️ PEACE MESSENGER ARRIVED!",
    peaceModalMsg: "A rival commander has sent an envoy offering an alliance and shared map vision!",
    acceptPeaceBtn: "🤝 Accept Peace Alliance",
    murderPeaceBtn: "🗡️ Murder Envoy (+150 Gold)",
    peaceAcceptedLog: "🕊️ Alliance accepted! Map visions merged with rival commander!",
    peaceMurderedLog: "🩸 Envoy murdered! Stole 150 GP, but rival gained +20% Holy Vengeance combat power against you!",
    holyVengeanceActiveLog: "⚡ Holy Vengeance Active! +20% combat power against treacherous rival!"
  },
  vi: {
    // Sandbox Tweaker
    sandboxTitle: "🧪 CÔNG CỤ THỬ NGHIỆM QUÂN ĐỘI",
    addWarriors: "+10 Lính",
    addGold: "+500 Vàng",
    addRations: "+20 Lương",
    addWizard: "+1 Pháp Sư",

    // Lobby & Setup
    lobbyTitle: "🏰 PHÁO ĐÀI PHÙ THỦY VƯƠNG",
    lobbySubtitle: "Tạo phòng đấu riêng hoặc nhập Mã Phòng để tham gia!",
    createRoom: "👑 TẠO PHÒNG MỚI",
    createRoomBtn: "🏰 TẠO PHÒNG MỚI",
    joinRoom: "⚔️ VÀO PHÒNG CÓ SẴN",
    joinRoomBtn: "⚔️ VÀO PHÒNG CÓ SẴN",
    roomCodeLabel: "Mã Phòng:",
    enterRoomCodePrompt: "Nhập Mã Phòng 4 ký tự (ví dụ: WKYG):",
    joinBtnText: "THAM GIA PHÒNG",
    backToMenuBtn: "⬅️ Quay Lại",
    hostBadge: "CHỦ PHÒNG 👑",
    guestBadge: "TƯỚNG LĨNH ⚔️",
    enterNamePrompt: "Tên Tướng Lĩnh:",
    chooseIconLabel: "Chọn Biểu Tượng Đại Diện:",
    readyBtnText: "🟢 CHỌN SẴN SÀNG",
    unreadyBtnText: "🔴 HỦY SẴN SÀNG",
    startGameBtnText: "⚔️ KHỞI CHẠY TRẬN ĐẤU",
    waitingForHost: "Đang chờ Chủ Phòng khởi chạy trận đấu...",
    waitingForPlayers: "Đang chờ tất cả người chơi nhấn SẴN SÀNG...",
    gameStartingNotice: "🚀 TẤT CẢ ĐÃ SẴN SÀNG! Đang tạo bản đồ & phân bổ vị trí...",
    mapSizeNotice: "Kích Thước Bản Đồ:",
    playerCountLabel: "Danh Sách Phòng:",
    enterName: "Nhập tên người chơi...",
    enterCode: "Nhập mã phòng 4 chữ cái...",
    chooseDifficulty: "Chọn Cấp Độ Khởi Đầu:",
    difficultyLvl: "Cấp",
    level1Desc: "Anh Hùng Tiên Tri (Dễ) - 50 Lính, 3 Trinh sát, 2 Mục sư, 500 Vàng, 30 Lương, Kiếm Diệt Rồng",
    level2Desc: "Tướng Lĩnh Dày Dạn (Thường) - 30 Lính, 2 Trinh sát, 1 Mục sư, 300 Vàng, 20 Lương",
    level3Desc: "Thám Hiểm Liều Lĩnh (Khó) - 15 Lính, 1 Trinh sát, 1 Mục sư, 150 Vàng, 10 Lương",
    level4Desc: "Sinh Tồn Đơn Lộc (Huyền Thoại) - 5 Lính, 1 Trinh sát, 0 Mục sư, 50 Vàng, 5 Lương",
    mapDifficulty: "Mức Khó Bản Đồ (1-20):",
    activePlayers: "Người Chơi Đang Trong Phòng:",
    backToLobby: "← Trở Về Phòng Chờ",

    // Terrain Names & Tooltips
    terrainPlains: "Đồng Bằng",
    terrainForest: "Rừng Rậm",
    terrainMountain: "Núi Cao",
    terrainLake: "Hồ Nước",
    terrainTown: "Thành Trị",
    terrainSanctuary: "Thánh Địa",
    terrainCitadel: "Pháo Đài",
    costLabel: "Chi Phí",
    unexploredLabel: "Chưa Thám Hiểm (Sương Mù)",

    // Viewport Controls
    zoomIn: "🔍 Phóng To",
    zoomOut: "🔍 Thu Nhỏ",
    centerCam: "🎯 Định Vị Người Chơi",

    // Header & Nav
    headerTitle: "🎮 ĐẤU TRƯỜNG PHÁO ĐÀI VƯƠNG GIẢ v0.0.3-ALPHA",
    headerSub: "Mô Phỏng Di Chuyển & Chợ Thương Nhân Trực Tiếp",
    seedLabel: "Mã Map Seed:",
    diffLabel: "Độ Khó (1-4):",
    posLabel: "📍 Vị Trí:",
    mfLabel: "⚡ Thể Lực (MF):",
    rationsLabel: "🌾 Lương Thực:",
    goldLabel: "💰 Vàng:",
    warriorsLabel: "⚔️ Binh Lính:",
    scoutsLabel: "🏹 Trinh Sát:",
    mulesLabel: "🫏 Lừa Thồ:",
    wizardsLabel: "🧙‍♂️ Pháp Sư:",
    clericsLabel: "📿 Mục Sư:",
    raidersLabel: "🗡️ Đạo Tặc:",
    raftLabel: "🚣 Bè Gỗ:",
    yes: "CÓ",
    no: "KHÔNG",
    sightLabel: "Tầm Nhìn:",
    navTip: "* Nhấp vào ô viền xanh để di chuyển. Nhấp ô hiện tại để nghỉ/vào lại chợ.",
    endTurnBtn: "🔒 KHÓA & KẾT THÚC LƯỢT",
    logHeader: "Nhật Ký Hành Động:",
    
    // Marketplace & Haggling
    shopTitle: "🏰 CHỢ THƯƠNG NHÂN THÀNH TRỊ",
    yourGold: "💰 Vàng Hiện Có:",
    bargainFor: "Trả giá cho:",
    yourBid: "Giá Bạn Trả:",
    quote: "Giá Thách:",
    offerBtn: "🤝 ĐẶT GIÁ NÀY",
    exitShopBtn: "Rời Chợ (Không Mua)",
    shopWelcome: "Chào mừng đến với Chợ Thành Trị!",
    notEnoughGold: "⚠️ Bạn không đủ Vàng để trả mức giá này!",

    // Shop Items
    itemRationsName: "Túi Lương Thực (10x)",
    itemRationsDesc: "10 phần ăn duy trì quân đội mỗi lượt.",
    itemWarriorsName: "Chiến Binh (5x)",
    itemWarriorsDesc: "Lực lượng chiến đấu giáp lá lá cận chiến.",
    itemScoutsName: "Trinh Sát Tinh Anh",
    itemScoutsDesc: "Tăng tầm nhìn bản đồ và né tránh đột kích.",
    itemClericsName: "Mục Sư Hồi Máu",
    itemClericsDesc: "Hồi phục vết thương quân sĩ sau trận đánh.",
    itemRaidersName: "Đạo Tặc Tập Kích",
    itemRaidersDesc: "Đơn vị lén lút cướp phá doanh trại đối thủ.",
    itemMulesName: "Lừa Thồ Hàng",
    itemMulesDesc: "Tăng sức chứa vàng túi đồ (+50 Vàng).",
    itemRaftName: "Bè Gỗ Vượt Sông + 4 Lừa",
    itemRaftDesc: "Cho phép di chuyển băng qua các ô Hồ Nước.",
    itemWizardName: "Đại Pháp Sư",
    itemWizardDesc: "Tăng +20% sức mạnh chiến đấu & chưởng lửa.",
    itemTeleportName: "Cuộn Bí Kíp Dịch Chuyển",
    itemTeleportDesc: "Dịch chuyển tức thời tới nơi.",
    itemSeeingName: "Phép Thuật Mở Tầm Nhìn",
    itemSeeingDesc: "Tạm thời soi sáng vùng đất bị mây mù che phủ.",

    // Merchant Feedback
    merchantHappy: "😊 Thương nhân vui vẻ đồng ý bán ngay lập tức!",
    merchantGroan: "🙂 Thương nhân cằn nhằn một chút nhưng chấp nhận bán.",
    merchantCounter: "🤨 Thương nhân chê rẻ. Giá mặc cả lại:",
    merchantAngry: "😡 'Cút khỏi tiệm tao ngay, đồ keo kiệt!' Thương nhân đuổi bạn ra ngoài!",
    merchantOffended: "😠 Thương nhân tự ái vì bị ép giá quá đáng. Đưa ra giá cứng:",

    // Modals & Citadel / Endgame
    transSuccess: "🎉 GIAO DỊCH THÀNH CÔNG",
    ejectedTitle: "🚨 BỊ BỊT MIỆNG ĐUỔI KHỎI CHỢ",
    acquiredText: "Đã sở hữu:",
    forText: "với giá",
    penaltyText: "Hình phạt:",
    penaltyDetail: "-1 Điểm Thể Lực (MF)",
    claimContinueBtn: "✅ OK, NHẬN MÓN HÀNG & TIẾP TỤC",
    leaveShopBtn: "🚪 OK, RỜI KHỎI CHỢ",
    citadelGateTitle: "🏰 CÔNG THÀNH PHÁO ĐÀI VƯƠNG GIẢ",
    citadelGateMsg: "Toàn quân đã tiếp cận Pháo Đài Bóng Tối của Witch King!",
    citadelHornBonus: "🎺 Phát hiện Tù Và Khai Mở! Tỷ lệ phá cổng tăng lên 75%!",
    citadelNoHornWarn: "⚠️ Không có Tù Và Khai Mở! Đột nhập hoàn toàn phụ thuộc vào Trinh Sát!",
    citadelBreachSuccess: "💥 PHÁ CỔNG THÀNH CÔNG! Toàn quân tràn vào pháo đài!",
    citadelBreachFailed: "🛡️ THẤT BẠI! Cổng pháo đài quá kiên cố, quân đội bị đẩy lùi (-1 MF)!",
    citadelSealedTitle: "🏰 CỔNG PHÁO ĐÀI PHẢN CÔNG!",
    citadelSealedMsg: "Cổng tối đã đẩy lùi quân đội của bạn! (Tù Và tăng 75% cơ hội phá cổng; Trinh Sát tăng 5%/con). Hãy thử lại!",
    citadelTitle: "🏰 PHÁO ĐÀI TỐI CỦA PHÙ THỦY VƯƠNG",
    citadelSubtitle: "Khám phá 16 căn phòng bí mật. Tìm Phù Thủy Vương và tránh Bẫy Dịch Chuyển!",
    roomCleared: "ĐÃ DỌN",
    teleportTrapTitle: "🌀 KÍCH HOẠT BẪY DỊCH CHUYỂN!",
    teleportTrapMsg: "Cổ tự ma thuật lóe sáng dưới chân, đẩy toàn bộ quân đội của bạn văng ra ngoài bản đồ!",
    duelDefeatTitle: "💀 BỊ PHÙ THỦY VƯƠNG ĐÁNH BẠI!",
    duelDefeatMsg: "Phép thuật cổ đại của Chúa Tể Bóng Tối đã đánh gục vị tướng của bạn! Tàn quân buộc phải rút lui về Thánh Địa để dưỡng thương.",
    logCitadelReentered: "🏰 Tiến vào lại Pháo Đài Tối...",
    roomSlain: "ĐÃ DIỆT",
    roomTrap: "BẪY",
    duelTitle: "⚔️ QUYẾT ĐẤU 1v1: PHÙ THỦY VƯƠNG",
    duelSubtitle: "Thắng 2/3 Hiệp! Chọn thế đánh chiến thuật để hạ gục Chúa Tể Bóng Tối:",
    stanceBlade: "⚔️ Tấn Công Kiếm",
    stanceShield: "🛡️ Đỡ Giáp",
    stanceSpell: "🔮 Chưởng Phép",
    duelRound: "Hiệp",
    duelYouChose: "Bạn chọn",
    duelBossChose: "Phù Thủy Vương chọn",
    roundWin: "🎉 Thắng Hiệp!",
    roundLoss: "💀 Thua Hiệp!",
    roundDraw: "🤝 Hòa Thế Đánh!",
    witchKingTitle: "👑 PHÙ THỦY VƯƠNG XUẤT HIỆN!",
    witchKingVictoryTitle: "👑 CHIẾN THẮNG! WITCH KING ĐÃ BỊ TIÊU DIỆT!",
    witchKingVictoryMsg: "Bạn đã tiêu diệt Chúa Tể Bóng Tối Shadow Lich, thu hồi Vương Miện & Ngọc Ấn Vương Giả! Vương quốc đã được giải phóng!",
    claimVictoryBtn: "🏆 NHẬN CHIẾN THẮNG TỐI CAO",
    gameVictoryTitle: "🏆 CHIẾN THẮNG BÁ CHỦ VƯƠNG QUỐC!",
    victoryMsg: "Bạn đã tiêu diệt Phù Thủy Vương và chinh phục toàn bộ Đấu Trường Pháo Đài! Danh tiếng của bạn truyền tụng vạn đời!",
    opponentWonTitle: "💀 TRẬN ĐẤU KẾT THÚC - THẤT BẠI!",
    opponentWonMsg: "Tướng lĩnh đối phương đã hạ gục Phù Thủy Vương và giành danh hiệu Bá Chủ Vương Quốc!",
    logWitchKingDefeated: "👑 ĐÃ HẠ GỤC PHÙ THỦY VƯƠNG! Giành chiến thắng tối thượng!",
    logCitadelSealed: "⚠️ Cổng Pháo Đài bị niêm phong! Cần có 🎺 Tù Và Khai Mở.",
    relicTitle: "🏛️ GIÀNH ĐƯỢC BẢO VẬT CỔ ĐẠI!",
    relicAcquiredMsg: "Bạn đã đánh bại Quái Vật Hộ Vệ và sở hữu Bảo Vật Huyền Thoại!",
    relicBootsName: "🥾 Giày Tàng Hình (Đi Rừng/Núi chỉ tốn 1 MF)",
    relicHornName: "🎺 Tù Và Khai Mở (Chìa Khóa Mở Cổng Pháo Đài)",
    relicSwordName: "🗡️ Thánh Kiếm Sức Mạnh (+50% Sức Mạnh Chiến Đấu)",
    relicArmorName: "🛡️ Thánh Giáp Phòng Thủ (Giảm 50% Thương Vong Quân Sĩ)",

    // PvE Combat & Harvesting
    combatTitle: "⚔️ ĐỤNG ĐỘ QUÁI VẬT HOANG DÃ",
    surpriseTitle: "🚨 PHÁT HIỆN ĐỘT KÍCH BẤT NGỜ!",
    surpriseMsg: "Trinh sát đã phát hiện quái vật phía trước!",
    spottedMonster: "Quái Vật Phát Hiện:",
    winRateEstimate: "Tỷ Lệ Thắng Dự Đoán:",
    retreatBtn: "🏃 RÚT LUI AN TOÀN",
    fleeMidCombatBtn: "🏃 THÁO CHẠY (-1 MF)",
    fightBtn: "⚔️ LAO VÀO NGHÊNH CHIẾN",
    attackRoundBtn: "🎲 ĐỔ XÚC XẮC TẤN CÔNG",
    victoryTitle: "🎉 CHIẾN THẮNG RỰC RỠ!",
    defeatTitle: "💀 QUÂN TIỀN TUYẾN THẤT THỦ!",
    harvestBtn: "🍖 THU HOẠCH THỊT QUÁI LÀM LƯƠNG THỰC",
    skipHarvestBtn: "⏭️ BỎ QUA & RỜI ĐI",
    safeMeatYield: "Lương thực sạch thu hoạch được:",
    toxicMeatWarning: "⚠️ CẢNH BÁO THỊT ĐỘC: Thu hoạch gấp đôi lương thực nhưng có nguy cơ trúng độc!",
    poisonedMsg: "🤢 TRÚNG ĐỘC! ĂN THỊT ĐỘC CHƯA CHẾ BIẾN LÀM SUY YẾU CƠ THỂ (-1 MF lượt sau)!",
    cleanEatMsg: "😋 Trinh sát đã chế biến sạch sẽ! Thu hoạch lương thực an toàn!",
    inedibleMsg: "🦴 Xác quái vật rỗng/không thể ăn được.",
    goldLootGained: "Vàng cướp được từ quái vật:",
    droppedGoldWarn: "⚠️ Rơi bớt Vàng do vượt quá sức chứa túi đồ! Đã rơi",
    droppedGoldModalTitle: "📦 VÀNG VƯỢT DUNG TÍCH ĐÃ RƠI XUỐNG ĐẤT!",
    droppedGoldModalMsg: "Quân đội của bạn đã hết sức chứa vàng! Số vàng dư thừa đã được để lại trên ô đất này. Hãy quay lại đây cùng Lừa Thồ hoặc Binh Lính để nhặt lại.",
    droppedAmountLabel: "Số Vàng Rơi Trên Đất:",
    locationLabel: "Tọa Độ Ô:",
    pickupGoldLog: "💰 Đã nhặt lại vàng trên đất! Thu hồi",
    goldCollectedModalTitle: "💰 ĐÃ NHẶT LẠI VÀNG TRÊN ĐẤT!",
    goldCollectedModalMsg: "Quân đội của bạn đã thu hồi lại số vàng thất lạc tại ô này!",
    goldCollectedAmountLabel: "Số Vàng Thu Hồi:",

    // Scrolls & Raiding
    castSeeingBtn: "📜 Phép Thuật Mở Tầm Nhìn",
    playerNameLabel: "Tên Người Chơi:",
    opponentsOnline: "Người Chơi Trong Phòng:",
    raidedByLog: "🚨 CẢNH BÁO! Doanh trại của bạn bị tập kích bởi",
    raidedYouLog: "🗡️ Tập Kích Thành Công! Bạn đã cướp doanh trại của",
    raidModalTitle: "🚨 DOANH TRẠI BỊ TẬP KÍCH BẤT NGỜ!",
    raidModalMsg: "Đạo tặc đối phương đã lén lút đột nhập doanh trại của bạn trong đêm!",
    raidOutOfRange: "⚠️ Đối thủ ở quá xa phạm vi tập kích (Phải ở trong vòng 3 ô)!",
    raidedByLabel: "Tập kích bởi:",
    goldStolenLabel: "Số Vàng Bị Cướp:",
    mulesLootedLabel: "Số Lừa Bị Bắt:",
    raidThwartedLog: "🛡️ TRINH SÁT BÁO ĐỘNG! Đã phát hiện và đánh đuổi đạo tặc đối phương!",
    raidThwartedAttackerLog: "🚨 Tập kích thất bại! Trinh sát đối phương đã phát hiện đạo tặc của bạn!",
    relicStolenLabel: "Bảo Vật Cổ Đại Bị Cướp:",
    townRumorTitle: "📜 BẢN TIN THÀNH TRỊ & THÁNH ĐỊA",
    townRumorMsg: "Thương nhân và đạo sĩ loan truyền những tin tức chấn động trên giang hồ:",
    logRumorClaimed: "đã đánh bại Trùm Hộ Vệ và đoạt lấy",
    logRumorStolen: "đã lén lút cướp lấy",
    logRumorFrom: "từ doanh trại của",
    opponentSpottedTitle: "🚨 TRINH SÁT PHÁT HIỆN ĐỐI THỦ!",
    opponentSpottedMsg: "Trinh sát phát hiện quân đội đối phương trong tầm nhìn!",
    drownModalTitle: "🌊 CHẾT ĐUỐI DƯỚI HỒ NƯỚC SÂU!",
    drownModalMsg: "Quân đội kiệt sức do vượt hồ không có Bè Gỗ! Áo giáp sắt kéo chìm quân sĩ làm rơi sạch Vàng. Tàn quân dạt vào bờ đất gần nhất.",
    drownLog: "🌊 Đã chết đuối dưới Hồ Nước! Đánh rơi sạch Vàng và dạt vào ô đất ven bờ",
    teleportTargetPrompt: "🌀 CHỌN ĐIỂM DỊCH CHUYỂN: Nhấp vào BẤT KỲ ô đất nào trên bản đồ!",
    teleportCancelBtn: "❌ Hủy Dịch Chuyển",
    castTeleportBtn: "🌀 Dịch Chuyển Về Thành Trị",
    raidCampBtn: "🗡️ Đạo Tặc Tập Kích Doanh Trại",
    logSeeingCast: "✨ Đã xé rách sương mù! Mở rộng tầm nhìn bán kính 8 ô xung quanh!",
    logTeleportCast: "🌀 Dịch Chuyển Tức Thời! Đưa toàn quân trở về an toàn!",
    logRaidSuccess: "🗡️ Đạo Tặc Tập Kích Thành Công! Cướp được +150 Vàng và +1 Lừa Thồ!",
    logNoScrolls: "⚠️ Bạn không sở hữu cuộn bí kíp phép thuật này!",

    // Monster Names
    monsterKobold: "Trinh Sát Kobold",
    monsterGoblin: "Lính Tiên Phong Goblin",
    monsterBugbear: "Kẻ Cướp Bugbear",
    monsterOrc: "Cuồng Chiến Binh Orc",
    monsterOwlbear: "Quái Bố Owlbear",
    monsterTroll: "Troll Hang Động",
    monsterGargoyle: "Quỷ Đá Gargoyle",
    monsterGiant: "Khổng Lồ Băng Băng",
    monsterChimera: "Quái Thú Chimera",
    monsterMindFlayer: "Quỷ Hút Não Mind Flayer",
    monsterDisplacer: "Báo Biến Hình Displacer",
    monsterCube: "Khối Nhầy Gelatinous",
    monsterDragon: "Rồng Đỏ Cổ Đại",
    monsterBeholder: "Quái Nhãn Beholder",
    monsterTarrasque: "Thảm Họa Tarrasque",
    monsterZombie: "Thây Ma Zombie",
    monsterSkeleton: "Chiến Binh Xương Khô",
    monsterMimic: "Rương Ma Mimic",
    monsterIronGolem: "Người Sắt Iron Golem",
    monsterLich: "Chúa Tể Bóng Tối Lich",

    // Action Logs & Manual
    logSpawn: "🏁 Khởi tạo bản đồ. Xuất phát tại Thành Trị",
    logMoved: "👟 Đã bước tới",
    logReentered: "🏰 Vào lại Chợ Thành Trị (-1 MF)! Mở cửa tiệm...",
    logRested: "⛺ Tạm nghỉ tại ô hiện tại",
    logEnteredTown: "🏰 Đặt chân vào Thành Trị! Mở Chợ Thương Nhân...",
    logPurchased: "🛒 Đã mua",
    logEjected: "😡 Bị thương nhân đuổi vì trả giá quá bèo! Trừ 1 MF!",
    logTurnEnded: "🌙 Kết thúc lượt. Tiêu thụ",
    logRations: "phần lương thực.",
    logStarvation: "⚠️ CHẠY ĂN TỪNG BỮA! Mất",
    logWarriorsLost: "Chiến Binh do chết đói!",
    logNewTurn: "☀️ Bắt đầu lượt mới! Thể lực hồi phục 3 MF.",
    waitingTurnLockTitle: "⏳ ĐÃ KHÓA LƯỢT - ĐANG CHỜ CÁC TƯỚNG KHÁC",
    waitingTurnLockMsg: "Bạn đã kết thúc lượt. Vui lòng chờ tất cả người chơi trong phòng nhấn KHÓA & KẾT THÚC LƯỢT...",
    openManualBtn: "📖 CẨM NANG & LUẬT CHƠI",
    manualTitle: "📜 CẨM NANG TƯỚNG LĨNH PHÁO ĐÀI",
    manualSecObjectiveTitle: "🏆 1. Mục Tiêu & Điều Kiện Thắng",
    manualSecObjectiveText: "Cạnh tranh trực tiếp với các tướng lĩnh khác trong phòng. Săn tìm 4 Bảo Vật Cổ Đại, phá cổng Pháo Đài Tối và đánh bại Phù Thủy Vương trong trận quyết đấu 1v1 để giành chiến thắng tối cao!",
    manualSecMovementTitle: "👟 2. Di Chuyển, Lương Thực & Sinh Tồn",
    manualSecMovementText: "Mỗi lượt cấp 3 điểm Thể Lực (MF). Đi thẳng tốn 1 MF, đi chéo tốn 2 MF, vào Núi Cao tốn thêm +1 MF. Cuối lượt, quân đội tiêu thụ Lương Thực (1 + Số Lính/10). Hết lương thực sẽ gây chết đói! Mục Sư giúp hồi máu quân sĩ. Mang Bè Gỗ cần 4 Lừa Thồ để vượt Hồ Nước.",
    manualSecShopTitle: "🏰 3. Chợ Thành Trị & Trả Giá",
    manualSecShopText: "Tiến vào Thành Trị để chiêu mộ quân, mua lương thực hoặc cuộn phép. Mỗi lần ghé thăm chỉ mua được 1 món. Kéo thanh trượt để mặc cả giá. Trả giá dưới 70% có nguy cơ bị thương nhân chửi, đuổi khỏi chợ và mất 1 MF!",
    manualSecMonstersTitle: "⚔️ 4. Quái Vật & Thu Hoạch Thịt",
    manualSecMonstersText: "Rừng Rậm (28%) và Núi Cao (80%) sẽ đụng độ quái vật. Sau chiến thắng, thu hoạch thịt làm Lương Thực: Quái Lành (Thịt Sạch 100%); Quái Độc (Gấp đôi lương thực nhưng nguy cơ trúng độc, trừ 1 MF lượt sau); Quái Rỗng (Không có thịt). Mỗi Trinh Sát giảm 5% nguy cơ trúng độc!",
    manualSecRelicsTitle: "🏛️ 5. Bảo Vật Cổ Đại (Diệt Phù Thủy Vương)",
    manualSecRelicsText: "Đánh bại Trùm Hộ Vệ Núi để sở hữu 4 Bảo Vật:\n• 🥾 Giày Tàng Hình: Đi Rừng & Núi chỉ tốn 1 MF.\n• 🗡️ Thánh Kiếm: Tăng +50% Sức Mạnh Chiến Đấu.\n• 🛡️ Thánh Giáp: Giảm 50% thương vong quân sĩ.\n• 🎺 Tù Và Khai Mở: Tăng tỷ lệ phá Cổng Pháo Đài lên 75%.",
    manualSecRaidingTitle: "🗡️ 6. Đột Kích Doanh Trại & Trinh Sát",
    manualSecRaidingText: "Khi ở trong phạm vi 3 ô với đối thủ, thả Đạo Tặc để cướp Vàng, Lừa Thồ và Bảo Vật! Đối thủ có Trinh Sát sẽ có 20%/con cơ hội cảnh báo và đánh đuổi đạo tặc. Bảo vật bị cướp sẽ tạo tin đồn ở Thành Trị!",
    manualSecCitadelTitle: "🏰 7. Chinh Phục Pháo Đài & Quyết Đấu",
    manualSecCitadelText: "Tiếp cận Pháo Đài và phá cổng bằng Tù Và (75%) hoặc Trinh Sát. Bên trong gồm 16 phòng bí mật, né Bẫy Dịch Chuyển văng ra ngoài! Mở ô Phù Thủy Vương để quyết đấu 1v1 thắng 2/3 hiệp: Kiếm (⚔️) khắc Phép (🔮), Phép khắc Giáp (🛡️), Giáp khắc Kiếm!",
    logRelicFound: "✨ QUÁI VẬT HỘ VỆ XUẤT HIỆN! Trùm thần thoại đang canh giữ Bảo Vật Cổ Đại!",
    logEncounterTrigger: "⚔️ Đụng độ quái vật hoang dã! Bắt đầu giao tranh!",
    logCombatWon: "🏆 Tiêu diệt sạch quái vật! Giành chiến thắng.",
    logRetreated: "🏃 Rút lui an toàn khỏi quái vật hoang dã.",

    // Diplomacy & Parley Strings
    parleyTitle: "🤝 ĐỘI QUÂN TRUNG LẬP XUẤT HIỆN",
    parleyElfMsg: "Tàn quân Tộc Tinh Linh (Elves) bước ra từ tán rừng rậm cổ thụ!",
    parleyDwarfMsg: "Tộc Người Lùn (Dwarves) vung búa tiến xuống từ đỉnh núi cao!",
    recruitElvesBtn: "🧝‍♂️ Chiêu Mộ Tinh Linh (+5 Quân)",
    recruitDwarvesBtn: "🪓 Chiêu Mộ Người Lùn (+5 Quân)",
    attackParleyBtn: "⚔️ Tấn Công Giao Tranh",
    ignoreParleyBtn: "🚶 Rời Đi Hòa Bình",
    sendPeaceBtn: "🕊️ Sứ Giả Hòa Bình",
    peaceModalTitle: "🕊️ SỨ GIẢ HÒA BÌNH ĐẾN DOANH TRẠI!",
    peaceModalMsg: "Tướng lĩnh đối phương gửi sứ giả tới đề nghị liên minh và chia sẻ tầm nhìn bản đồ!",
    acceptPeaceBtn: "🤝 Chấp Nhận Liên Minh",
    murderPeaceBtn: "🗡️ Sát Hại Sứ Giả (+150 Vàng)",
    peaceAcceptedLog: "🕊️ Đã ký hòa ước! Mở rộng tầm nhìn bản đồ chung với đối thủ!",
    peaceMurderedLog: "🩸 Đã giết sứ giả! Cướp 150 Vàng nhưng đối thủ nhận điểm nộ +20% Sức Mạnh Thánh Phẫn!",
    holyVengeanceActiveLog: "⚡ Phẫn Nộ Trả Thù! Tăng +20% sức mạnh chiến đấu chống lại kẻ phản Bội!"
  }
};